CREATE TABLE users (
    user_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    email VARCHAR2(100),
    PRIMARY KEY (user_id)
);

CREATE TABLE posts (
    post_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    user_id NUMBER,
    title VARCHAR2(200),
    content CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (post_id),
    FOREIGN KEY (user_id) REFERENCES users(user_id)
);
